/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/W2k16kg81uK
 */
import Link from "next/link"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select } from "@/components/ui/select"
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"

export function Business() {
  return (
    <div className="w-full py-12">
      <div className="mx-auto px-4 max-w-7xl">
        <div className="space-y-6">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold">Sign up your business for Shadcn Pro</h1>
            <p className="text-gray-500 dark:text-gray-400">
              Already have an account?
              <Link className="underline" href="#">
                Sign in
              </Link>
            </p>
          </div>
          <Card>
            <CardHeader>
              <h2 className="text-base font-semibold">Business Information</h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">Enter your business information below</p>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="business-name">Business Name</Label>
                  <Input id="business-name" required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="website">Website</Label>
                  <Input id="website" placeholder="https://example.com" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="industry">Industry</Label>
                  <Select id="industry">
                    <option value="retail">Retail</option>
                    <option value="technology">Technology</option>
                    <option value="finance">Finance</option>
                    <option value="healthcare">Healthcare</option>
                    <option value="other">Other</option>
                  </Select>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <h2 className="text-base font-semibold">Contact Information</h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">Enter your contact information below</p>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="contact-name">Contact Name</Label>
                  <Input id="contact-name" required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="contact-email">Contact Email</Label>
                  <Input id="contact-email" required type="email" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="phone">Phone</Label>
                  <Input id="phone" placeholder="e.g. (555) 123-4567" />
                </div>
              </div>
            </CardContent>
          </Card>
          <div className="space-y-4">
            <Checkbox id="terms" />
            <div className="text-sm">
              By creating an account, you agree to the
              <Link className="underline" href="#">
                Terms of Service
              </Link>
              and
              <Link className="underline" href="#">
                Privacy Policy
              </Link>
              .
            </div>
            <Button className="w-full">Sign up</Button>
          </div>
        </div>
      </div>
    </div>
  )
}
